default:
    active-within: 24h0m0s
    social-login: google-oauth2
output:
    color:
        fail: '#ff0000'
        pass: '#00ff00'
        warn: '#ffa500'
    records:
        notable: []
platform:
    api: https://console-api.enforce.dev
    audience: https://console-api.enforce.dev
    console: https://console.enforce.dev
    issuer: https://issuer.enforce.dev
    registry: https://cgr.dev
    timestamp-authority: https://tsa.enforce.dev
