#!/bin/sh

file=$1
w=$2
h=$3
x=$4
y=$5

case "$1" in
    *.jpg|*.png) kitty +icat --silent --transfer-mode file --place "${w}x${h}@${x}x${y}" "$file" ;;
    *) bat --color always --style changes,numbers -r :"$w" "$file";;
esac
